name: Compilar y publicar en rama build

on:
  pull_request:
    types: [closed] # Ejecutar cuando se cierre un pull request
    branches:
      - main # Solo cuando el PR es hacia main

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Compilar y Publicar
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm install

      - name: Compilar proyecto
        run: npm run build
        env:
          NODE_ENV: production

      - name: Publicar a rama build
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: public # Carpeta que se publicará en la rama build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"
          SQUASH_HISTORY: true